#!/data/data/com.termux/files/usr/bin/sh
## This file is executed during VNC server
## startup.
mate-session &


######################################################
# Launch terminal emulator Aterm.
# Requires package 'aterm'.
#aterm -geometry 80x24+10+10 -ls &

# Launch Tab Window Manager.
# Requires package 'xorg-twm'.
#twm &
